### PR TITLE
ExprMerchantRecipes - cleanup and fix

### LINKED ISSUE #616: [BUG] merchant break
### What happened?

[20:39:36 ERROR]: #!#! [Skript] Severe Error:
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Something went horribly wrong with Skript.
[20:39:36 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:39:36 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:39:36 ERROR]: #!#! Here is full list of them:
[20:39:36 ERROR]: #!#! SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee)
[20:39:36 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:39:36 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:39:36 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:39:36 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:39:36 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:39:36 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Stack trace:
[20:39:36 ERROR]: #!#! java.lang.NullPointerException: Cannot load from object array because "delta" is null
[20:39:36 ERROR]: #!#!     at SkBee-3.4.3.jar//com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipes.change(ExprMerchantRecipes.java:107)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:289)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[20:39:36 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[20:39:36 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[20:39:36 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:39:36 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:39:36 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:39:36 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$4.performInteraction(PlayerConnection.java:2794)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2849)
[20:39:36 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161)
[20:39:36 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2783)
[20:39:36 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[20:39:36 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[20:39:36 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:39:36 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:39:36 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[20:39:36 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1465)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1388)
[20:39:36 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1366)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1255)
[20:39:36 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[20:39:36 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Version Information:
[20:39:36 ERROR]: #!#!   Skript: 2.8.4 (latest)
[20:39:36 ERROR]: #!#!     Flavor: skriptlang-github
[20:39:36 ERROR]: #!#!     Date: 11:03:52.948789700
[20:39:36 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[20:39:36 ERROR]: #!#!   Minecraft: 1.20.4
[20:39:36 ERROR]: #!#!   Java: 17.0.10 (OpenJDK 64-Bit Server VM 17.0.10+7)
[20:39:36 ERROR]: #!#!   OS: Linux amd64 6.1.0-18-amd64
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Server platform: Paper
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Current node: null
[20:39:36 ERROR]: #!#! Current item: set merchant recipe loop-value of {merchant::%the player%} (as java.lang.Object) to {ferretsdaily::recipe::%loop-value%} (as org.bukkit.inventory.MerchantRecipe)
[20:39:36 ERROR]: #!#! Current trigger: right click on armor stand (rightclick on [[entitydata:armor stand]]) (tradeingtest.sk, line 12)
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Thread: Server thread
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! Language: english
[20:39:36 ERROR]: #!#! Link parse mode: DISABLED
[20:39:36 ERROR]: #!#!
[20:39:36 ERROR]: #!#! End of Error.
[20:39:36 ERROR]: #!#!

### Steps to reproduce

~~1.open a merchant with verrables for items idk~~
*edit by Fusezion*
The issue stems from ExprMerchantRecipes more notably the `merchant recipe %number% of %merchant/entity%` syntax where a delta issue was not correctly handled by the internal code.

```
on skript start:
    loop 10 times:
        set ingredients of merchant recipe {ferretsdaily::recipe::%loop-value%} to {ferretsdaily::materal::1::%loop-value%} and {ferretsdaily::materal::2::%loop-value%}
        set {ferretsdaily::result::%loop-value%} to result item of merchant recipe {ferretsdaily::recipe::%loop-value%}

on right click on armor stand:
    if event-entity have the scoreboard tag "trade":
        set {merchant::%player%} to new merchant named "Le-Merchant"
        if {-team::%player%} = "ferrets":
            broadcast "no"
            loop 10 times:
                if {-team::%player%::level} > {ferretsdaily::unlocks::%loop-value%}:
                    set merchant recipe loop-value of {merchant::%player%} to {ferretsdaily::recipe::%loop-value%}
            open merchant {merchant::%player%} to player

command /ferrets:
    trigger:
        set {ferretsdaily::unlocks::1} to 0
        set {ferretsdaily::materal::1::1} to dirt
        set {ferretsdaily::materal::2::1} to dirt
        set {ferretsdaily::result::1} to diamond
        set {-team::%player%} to "ferrets"
        set {-team::%player%::level} to 100
        broadcast {-team::%player%}
        open merchant {merchant::%player%} to player
```

### Expected behavior

not to give off a error

### SkBee Info

image

### PR DESCRIPTION
**Pull request by Fusezion**
Omg, where do I even start with this class. For starters this pr aims to fix the issue mentioned in #616. Somewhere within the 3 places `delta` was used there was cases where delta wasn't set, this seems most likely to stem from `delete` changer not existing but #616 proves it existed under the set changer as well.

## Bug Fix
Honestly I'm not 100% sure what the issue was but with how that class was actually set up it wouldn't shock me if a bitcoin miner existed inside it. however after messing around and cleaning it up it seems like the issue was solved and more proper checks were created. The systems internally were heavily a mess and melded together as such they've been split this allowed introduction of the `delete` change into `merchant recipe x of y` expression.

## Enhancements
This pr adds 2 *minor* enhancements first one being plural support, don't get me even started on how effing annoying this was to add but it's now added. Lastly similar to the nbt tag acceptchange method a new error message is now sent when using `add` outside of `merchant recipes of x` to further explain why it won't work. And you know what why not a third, docs now explicitly state you shouldn't be trying to set recipe of a non existent slot in the merchant that's what the add changer is for.

## Developer Note
In the future I believe it'll be best to implement a custom comparator for merchant recipes that can be used for more coherent comparisons. Since the merchant class doesn't override equals it follows the default usage which makes this fail rather than pass. I believe the comparator should compare result and ingredients while ignoring max uses, current uses, and other special values. If you believe enforcing those special values is the right direction, we can see in the future.
```
on load:
    set {_recipe1} to merchant recipe with result stone with max uses 10
    set {_recipe2} to merchant recipe with result stone with max uses 10
    set ingredients of merchant recipe {_recipe1} to bedrock and diamond
    set ingredients of merchant recipe {_recipe2} to bedrock and diamond
    if {_recipe1} is {_recipe2}:
        broadcast "They're the same damn thing"
    else:
        broadcast "It's one or the other guy man thing"
```
image

### CODE REVIEW

File: src/main/java/com/shanebeestudios/skbee/elements/villager/expressions/ExprMerchantRecipes.java [hunk 1]
```diff
@@ -23,105 +23,123 @@
...
+    public Class<?>[] acceptChange(ChangeMode mode) {
+        if (this.recipe == null) {
+            return switch (mode) {
+                case ADD, SET, DELETE -> CollectionUtils.array(MerchantRecipe[].class);
+                default -> null;
+            };
+        }
+        switch (mode) {
+            case SET, DELETE:
+                return CollectionUtils.array(MerchantRecipe.class);
```
Comment (Fusezion) [inline src/main/java/com/shanebeestudios/skbee/elements/villager/expressions/ExprMerchantRecipes.java:86]: The reason I'm creating a new switch here is to prevent cases like `set merchant recipe 1 of {_merchant} to {_recipe1}, {_recipe2}, {_recipe3}` which is something even skript doesn't properly handle in cases like `set player's tool to diamond and emeradl`

**Review by ShaneBeee — APPROVED** [review]
I have no clue what's going on here, so imma just say 👍🏻

**Comment by Fusezion** [comment]
> I have no clue what's going on here, so imma just say 👍🏻 and trust you

my impression when I first saw this class as well
